spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.sq.recorder.pojo
  configuration:
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto