spring:
  mvc:
    servlet:
      load-on-startup: 0
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    static-path-pattern: /**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations:
      - classpath:/static/
      - file:///${project.upload.base-path}

project:
  upload:
    base-path: /Users/zhushuangquan/Desktop/upload/
    image-path: img/
    video-path: video/