server:
  port: 9000

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredPatterns: /*-server/**
  routes:
    product-server-route:
      path: /product/**
      serviceId: product-server
    order-server-route:
      path: /order/**
      serviceId: order-server
  sensitive-headers: