server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/crmdemo
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 6
  mvc:
    pathmatch:
      use-registered-suffix-pattern: true
      use-suffix-pattern: true
mybatis:
  mapper-locations: classpath:com/coderZsq/crm/mapper/*.xml
  type-aliases-package: com.coderZsq.crm.domain
  config-location: classpath:mybatis-cfg.xml
shiro:
  hash-algorithm-name: md5
  hash-iterations: 1
  cookie-name: token
  cookie-path: /
  cookie-domain: localhost
  cookie-max-age: 310000
  cache-manager-config-file: classpath:shiro-ehcache.xml
  login-url: /login.do