spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/imaginist?serverTimezone=GMT%2B8&characterEncoding=UTF-8

server:
  port: 8080

logging:
  level:
    com.sq.imaginist: debug

imaginist:
  cfg:
    cors-origins:
      - http://localhost:3000
  upload:
    base-path: /Users/zhushuangquan/Codes/GitHub/coderZsq.practice.server/imaginist/
    upload-path: upload/
    image-path: img/
    video-path: video/