server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 172.16.21.175:9092,172.16.21.175:9093,172.16.21.175:9094
    producer: # 生产者
      retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
      batch-size: 16384
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: testGroup
      enable-auto-commit: true
logging:
  level:
    root: info