spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/nonghang
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 6
server:
  port: 7001
rocketmq:
  name-server: 172.16.21.175:9876

logging:
  level:
    com.nonghang: debug
