server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://e.coding.net/dtid_ada36270f1f70012/cloud-config/cloud-config.git
          username:
          password:
    stream:
      rocket:
        binder:
          name-server: 172.16.21.175:9876
        bindings:
          springCloudBusInput:
            consumer:
              broadcasting: true
      bindings:
        springCloudBusInput:
          group: test-group
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
