spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/gonghang
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 6
server:
  port: 7002
rocketmq:
  name-server: 172.16.21.175:9876
  producer:
    group: gonghang-group
logging:
  level:
    com.gonghang: debug