spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gonghang
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
  application:
    name: gonghang-server
server:
  port: 7001

logging:
  level:
    com.sq.demo: debug
dubbo:
  application:
    name: gonghang-provider
  registry:
    address: nacos://127.0.0.1:8848
    check: true
  protocol:
    name: dubbo
    port: 20880
    host: 172.16.21.175

seata:
  enabled: true
  application-id: gonghang-server
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace:
      username: "nacos"
      password: "nacos"
