server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/redisdemo
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 6
  mvc:
    pathmatch:
      use-registered-suffix-pattern: true
      use-suffix-pattern: true
  redis:
    cluster:
      nodes: 172.16.21.175:7000,172.16.21.175:7001,172.16.21.175:7002,172.16.21.175:7003,172.16.21.175:7004,172.16.21.175:7005
    lettuce:
      pool:
        max-wait: 15000
        max-idle: 10
        max-active: 10
        min-idle: 10